### ISSUE TITLE
怎么运行？

### ISSUE THREAD

**Issue by yangkai77** [oyai32/course#1]
这个项目怎么部署运行啊，在你那买了sql文件不知道怎么运行这个项目，我运在登录界面点击登录的时候就出现这样：
![image](https://user-images.githubusercontent.com/57835879/236605929-5b38822b-43e1-4582-84c7-d359df55cc44.png)

**Comment by oyai32** [comment]
README.md 里写了操作步骤。
而且这个项目很老了，我当时是用的 tomcat。

另外，买了 sql 文件？我不是提供了测试 sql 吗？

**Comment by yangkai77** [comment]
> README.md里写了操作步骤。 而且这个项目很老了，我当时是用的tomcat。
> 
> 另外，买了sql文件？我不是提供了测试sql吗？



> README.md里写了操作步骤。 而且这个项目很老了，我当时是用的tomcat。
> 
> 另外，买了sql文件？我不是提供了测试sql吗？

可以加你一个联系方式嘛，我实在是运行不起来，有报酬求求了
![image](https://user-images.githubusercontent.com/57835879/236114708-79ae985d-b077-47ad-b04c-fd9bfb2b3bd1.png)

**Comment by yangkai77** [comment]
> README.md 里写了操作步骤。 而且这个项目很老了，我当时是用的 tomcat。
> 
> 另外，买了 sql 文件？我不是提供了测试 sql 吗？

在吗大佬

**Comment by yangkai77** [comment]
求求了
![Uploading image.png…]()

**Comment by yangkai77** [comment]
在吗
![image](https://user-images.githubusercontent.com/57835879/236386975-a684918c-a876-4bc9-8223-4b00b7f68685.png)

**Comment by Yuzheng98** [comment]
qq 860238981 你加我我帮你看看

**Comment by yangkai77** [comment]
> qq 860238981 你加我我帮你看看
加你了大佬，同意一下十万火急非常感谢您的帮助！

**Comment by yangkai77** [comment]
> qq 860238981 你加我我帮你看看

可以回我一下不大佬

**Comment by yangkai77** [comment]
已经成功解决问题感谢各位大佬支撑和指点。
